use core::default::Default;

const ELF_MAGIC: [u8;4] = [0x7Fu8, b'E', b'L', b'F'];

#[derive(PartialEq, Debug)]
pub enum ElfClass {
    ElfClassNone,
    ElfClass32,
    ElfClass64,
}

#[derive(PartialEq, Debug)]
pub enum ElfData {
    ElfDataNone,
    ElfData2Lsb,
    ElfData2Msb,
}

#[derive(PartialEq, Debug)]
pub enum ElfType {
    ElfTypeNone,
    ElfTypeRel,
    ElfTypeExec,
    ElfTypeDyn,
    ElfTypeCore,
    ElfTypeLoOs,
    ElfTypeHiOs,
    ElfTypeLoProc,
    ElfTypeHiProc,
}

#[derive(PartialEq, Debug)]
pub enum ElfMachine {
    ElfMachineNONE,
    ElfMachineM32,
    ElfMachineSPARC,
    ElfMachine386,
    ElfMachine68K,
    ElfMachine88K,
    ElfMachineIAMCU,
    ElfMachine860,
    ElfMachineMIPS,
    ElfMachineS370,
    ElfMachineMipsRs3Le,
    ElfMachinePARISC,
    ElfMachineVPP500,
    ElfMachineSPARC32PLUS,
    ElfMachine960,
    ElfMachinePPC,
    ElfMachinePPC64,
    ElfMachineS390,
    ElfMachineSPU,
    ElfMachineV800,
    ElfMachineFR20,
    ElfMachineRH32,
    ElfMachineRCE,
    ElfMachineARM,
    ElfMachineFakeAlpha,
    ElfMachineSH,
    ElfMachineSPARCV9,
    ElfMachineTRICORE,
    ElfMachineARC,
    ElfMachineH8300,
    ElfMachineH8300H,
    ElfMachineH8S,
    ElfMachineH8500,
    ElfMachineIA64,
    ElfMachineMipsX,
    ElfMachineCOLDFIRE,
    ElfMachine68HC12,
    ElfMachineMMA,
    ElfMachinePCP,
    ElfMachineNCPU,
    ElfMachineNDR1,
    ElfMachineSTARCORE,
    ElfMachineME16,
    ElfMachineST100,
    ElfMachineTINYJ,
    ElfMachineX8664,
    ElfMachinePDSP,
    ElfMachinePDP10,
    ElfMachinePDP11,
    ElfMachineFX66,
    ElfMachineST9PLUS,
    ElfMachineST7,
    ElfMachine68HC16,
    ElfMachine68HC11,
    ElfMachine68HC08,
    ElfMachine68HC05,
    ElfMachineSVX,
    ElfMachineST19,
    ElfMachineVAX,
    ElfMachineCRIS,
    ElfMachineJAVELIN,
    ElfMachineFIREPATH,
    ElfMachineZSP,
    ElfMachineMMIX,
    ElfMachineHUANY,
    ElfMachinePRISM,
    ElfMachineAVR,
    ElfMachineFR30,
    ElfMachineD10V,
    ElfMachineD30V,
    ElfMachineV850,
    ElfMachineM32R,
    ElfMachineMN10300,
    ElfMachineMN10200,
    ElfMachinePJ,
    ElfMachineOPENRISC,
    ElfMachineArcCompact,
    ElfMachineXTENSA,
    ElfMachineVIDEOCORE,
    ElfMachineTmmGpp,
    ElfMachineNS32K,
    ElfMachineTPC,
    ElfMachineSNP1K,
    ElfMachineST200,
    ElfMachineIP2K,
    ElfMachineMAX,
    ElfMachineCR,
    ElfMachineF2MC16,
    ElfMachineMSP430,
    ElfMachineBLACKFIN,
    ElfMachineSeC33,
    ElfMachineSEP,
    ElfMachineARCA,
    ElfMachineUNICORE,
    ElfMachineEXCESS,
    ElfMachineDXP,
    ElfMachineAlteraNios2,
    ElfMachineCRX,
    ElfMachineXGATE,
    ElfMachineC166,
    ElfMachineM16C,
    ElfMachineDSPIC30F,
    ElfMachineCE,
    ElfMachineM32C,
    ElfMachineTSK3000,
    ElfMachineRS08,
    ElfMachineSHARC,
    ElfMachineECOG2,
    ElfMachineSCORE7,
    ElfMachineDSP24,
    ElfMachineVIDEOCORE3,
    ElfMachineLATTICEMICO32,
    ElfMachineSeC17,
    ElfMachineTiC6000,
    ElfMachineTiC2000,
    ElfMachineTiC5500,
    ElfMachineTiARP32,
    ElfMachineTiPRU,
    ElfMachineMmdspPlus,
    ElfMachineCypressM8C,
    ElfMachineR32C,
    ElfMachineTRIMEDIA,
    ElfMachineQDSP6,
    ElfMachine8051,
    ElfMachineSTXP7X,
    ElfMachineNDS32,
    ElfMachineECOG1X,
    ElfMachineMAXQ30,
    ElfMachineXIMO16,
    ElfMachineMANIK,
    ElfMachineCRAYNV2,
    ElfMachineRX,
    ElfMachineMETAG,
    ElfMachineMcstElbrus,
    ElfMachineECOG16,
    ElfMachineCR16,
    ElfMachineETPU,
    ElfMachineSLE9X,
    ElfMachineL10M,
    ElfMachineK10M,
    ElfMachineAARCH64,
    ElfMachineAVR32,
    ElfMachineSTM8,
    ElfMachineTILE64,
    ElfMachineTILEPRO,
    ElfMachineMICROBLAZE,
    ElfMachineCUDA,
    ElfMachineTILEGX,
    ElfMachineCLOUDSHIELD,
    ElfMachineCorea1st,
    ElfMachineCorea2nd,
    ElfMachineARCV2,
    ElfMachineOPEN8,
    ElfMachineRL78,
    ElfMachineVIDEOCORE5,
    ElfMachine78KOR,
    ElfMachine56800EX,
    ElfMachineBA1,
    ElfMachineBA2,
    ElfMachineXCORE,
    ElfMachineMchpPic,
    ElfMachineINTELGT,
    ElfMachineKM32,
    ElfMachineKMX32,
    ElfMachineEMX16,
    ElfMachineEMX8,
    ElfMachineKVARC,
    ElfMachineCDP,
    ElfMachineCOGE,
    ElfMachineCOOL,
    ElfMachineNORC,
    ElfMachineCsrKalimba,
    ElfMachineZ80,
    ElfMachineVISIUM,
    ElfMachineFT32,
    ElfMachineMOXIE,
    ElfMachineAMDGPU,
    ElfMachineRISCV,
    ElfMachineBPF,
    ElfMachineCSKY,
}

#[derive(PartialEq, Debug)]
pub enum ElfVersion {
    ElfVersionNone,
    ElfVersionCurrent,
}

#[repr(C)]
pub struct ElfHeaderCommon {
    magic: [u8;4],
    _class: u8,
    _data_encoding: u8,
    version: u8,
    os_abi: u8,
    abi_version: u8,
    pad: [u8;7],
    _e_type: u16,
    _e_machine: u16,
    _e_version: u32,
}

impl ElfHeaderCommon {
    pub fn valid_magic(&self) -> bool {
        return self.magic == ELF_MAGIC;
    }

    pub fn class(&self) -> ElfClass {
        match self._class {
            1 => ElfClass::ElfClass32,
            2 => ElfClass::ElfClass64,
            _ => ElfClass::ElfClassNone,
        }
    }

    pub fn data_encoding(&self) -> ElfData {
        match self._data_encoding {
            1 => ElfData::ElfData2Lsb,
            2 => ElfData::ElfData2Msb,
            _ => ElfData::ElfDataNone,
        }
    }

    pub fn e_type(&self) -> ElfType {
        match self._e_type {
            1 => ElfType::ElfTypeRel,
            2 => ElfType::ElfTypeExec,
            3 => ElfType::ElfTypeDyn,
            4 => ElfType::ElfTypeCore,
            0xFE00 => ElfType::ElfTypeLoOs,
            0xFEFF => ElfType::ElfTypeHiOs,
            0xFF00 => ElfType::ElfTypeLoProc,
            0xFFFF => ElfType::ElfTypeHiProc,
            _ => ElfType::ElfTypeNone,
        }
    }

    pub fn e_machine(&self) -> ElfMachine {
        match self._e_machine {
            1 => ElfMachine::ElfMachineM32,
            2 => ElfMachine::ElfMachineSPARC,
            3 => ElfMachine::ElfMachine386,
            4 => ElfMachine::ElfMachine68K,
            5 => ElfMachine::ElfMachine88K,
            6 => ElfMachine::ElfMachineIAMCU,
            7 => ElfMachine::ElfMachine860,
            8 => ElfMachine::ElfMachineMIPS,
            9 => ElfMachine::ElfMachineS370,
            10 => ElfMachine::ElfMachineMipsRs3Le,
            15 => ElfMachine::ElfMachinePARISC,
            17 => ElfMachine::ElfMachineVPP500,
            18 => ElfMachine::ElfMachineSPARC32PLUS,
            19 => ElfMachine::ElfMachine960,
            20 => ElfMachine::ElfMachinePPC,
            21 => ElfMachine::ElfMachinePPC64,
            22 => ElfMachine::ElfMachineS390,
            23 => ElfMachine::ElfMachineSPU,
            36 => ElfMachine::ElfMachineV800,
            37 => ElfMachine::ElfMachineFR20,
            38 => ElfMachine::ElfMachineRH32,
            39 => ElfMachine::ElfMachineRCE,
            40 => ElfMachine::ElfMachineARM,
            41 => ElfMachine::ElfMachineFakeAlpha,
            42 => ElfMachine::ElfMachineSH,
            43 => ElfMachine::ElfMachineSPARCV9,
            44 => ElfMachine::ElfMachineTRICORE,
            45 => ElfMachine::ElfMachineARC,
            46 => ElfMachine::ElfMachineH8300,
            47 => ElfMachine::ElfMachineH8300H,
            48 => ElfMachine::ElfMachineH8S,
            49 => ElfMachine::ElfMachineH8500,
            50 => ElfMachine::ElfMachineIA64,
            51 => ElfMachine::ElfMachineMipsX,
            52 => ElfMachine::ElfMachineCOLDFIRE,
            53 => ElfMachine::ElfMachine68HC12,
            54 => ElfMachine::ElfMachineMMA,
            55 => ElfMachine::ElfMachinePCP,
            56 => ElfMachine::ElfMachineNCPU,
            57 => ElfMachine::ElfMachineNDR1,
            58 => ElfMachine::ElfMachineSTARCORE,
            59 => ElfMachine::ElfMachineME16,
            60 => ElfMachine::ElfMachineST100,
            61 => ElfMachine::ElfMachineTINYJ,
            62 => ElfMachine::ElfMachineX8664,
            63 => ElfMachine::ElfMachinePDSP,
            64 => ElfMachine::ElfMachinePDP10,
            65 => ElfMachine::ElfMachinePDP11,
            66 => ElfMachine::ElfMachineFX66,
            67 => ElfMachine::ElfMachineST9PLUS,
            68 => ElfMachine::ElfMachineST7,
            69 => ElfMachine::ElfMachine68HC16,
            70 => ElfMachine::ElfMachine68HC11,
            71 => ElfMachine::ElfMachine68HC08,
            72 => ElfMachine::ElfMachine68HC05,
            73 => ElfMachine::ElfMachineSVX,
            74 => ElfMachine::ElfMachineST19,
            75 => ElfMachine::ElfMachineVAX,
            76 => ElfMachine::ElfMachineCRIS,
            77 => ElfMachine::ElfMachineJAVELIN,
            78 => ElfMachine::ElfMachineFIREPATH,
            79 => ElfMachine::ElfMachineZSP,
            80 => ElfMachine::ElfMachineMMIX,
            81 => ElfMachine::ElfMachineHUANY,
            82 => ElfMachine::ElfMachinePRISM,
            83 => ElfMachine::ElfMachineAVR,
            84 => ElfMachine::ElfMachineFR30,
            85 => ElfMachine::ElfMachineD10V,
            86 => ElfMachine::ElfMachineD30V,
            87 => ElfMachine::ElfMachineV850,
            88 => ElfMachine::ElfMachineM32R,
            89 => ElfMachine::ElfMachineMN10300,
            90 => ElfMachine::ElfMachineMN10200,
            91 => ElfMachine::ElfMachinePJ,
            92 => ElfMachine::ElfMachineOPENRISC,
            93 => ElfMachine::ElfMachineArcCompact,
            94 => ElfMachine::ElfMachineXTENSA,
            95 => ElfMachine::ElfMachineVIDEOCORE,
            96 => ElfMachine::ElfMachineTmmGpp,
            97 => ElfMachine::ElfMachineNS32K,
            98 => ElfMachine::ElfMachineTPC,
            99 => ElfMachine::ElfMachineSNP1K,
            100 => ElfMachine::ElfMachineST200,
            101 => ElfMachine::ElfMachineIP2K,
            102 => ElfMachine::ElfMachineMAX,
            103 => ElfMachine::ElfMachineCR,
            104 => ElfMachine::ElfMachineF2MC16,
            105 => ElfMachine::ElfMachineMSP430,
            106 => ElfMachine::ElfMachineBLACKFIN,
            107 => ElfMachine::ElfMachineSeC33,
            108 => ElfMachine::ElfMachineSEP,
            109 => ElfMachine::ElfMachineARCA,
            110 => ElfMachine::ElfMachineUNICORE,
            111 => ElfMachine::ElfMachineEXCESS,
            112 => ElfMachine::ElfMachineDXP,
            113 => ElfMachine::ElfMachineAlteraNios2,
            114 => ElfMachine::ElfMachineCRX,
            115 => ElfMachine::ElfMachineXGATE,
            116 => ElfMachine::ElfMachineC166,
            117 => ElfMachine::ElfMachineM16C,
            118 => ElfMachine::ElfMachineDSPIC30F,
            119 => ElfMachine::ElfMachineCE,
            120 => ElfMachine::ElfMachineM32C,
            131 => ElfMachine::ElfMachineTSK3000,
            132 => ElfMachine::ElfMachineRS08,
            133 => ElfMachine::ElfMachineSHARC,
            134 => ElfMachine::ElfMachineECOG2,
            135 => ElfMachine::ElfMachineSCORE7,
            136 => ElfMachine::ElfMachineDSP24,
            137 => ElfMachine::ElfMachineVIDEOCORE3,
            138 => ElfMachine::ElfMachineLATTICEMICO32,
            139 => ElfMachine::ElfMachineSeC17,
            140 => ElfMachine::ElfMachineTiC6000,
            141 => ElfMachine::ElfMachineTiC2000,
            142 => ElfMachine::ElfMachineTiC5500,
            143 => ElfMachine::ElfMachineTiARP32,
            144 => ElfMachine::ElfMachineTiPRU,
            160 => ElfMachine::ElfMachineMmdspPlus,
            161 => ElfMachine::ElfMachineCypressM8C,
            162 => ElfMachine::ElfMachineR32C,
            163 => ElfMachine::ElfMachineTRIMEDIA,
            164 => ElfMachine::ElfMachineQDSP6,
            165 => ElfMachine::ElfMachine8051,
            166 => ElfMachine::ElfMachineSTXP7X,
            167 => ElfMachine::ElfMachineNDS32,
            168 => ElfMachine::ElfMachineECOG1X,
            169 => ElfMachine::ElfMachineMAXQ30,
            170 => ElfMachine::ElfMachineXIMO16,
            171 => ElfMachine::ElfMachineMANIK,
            172 => ElfMachine::ElfMachineCRAYNV2,
            173 => ElfMachine::ElfMachineRX,
            174 => ElfMachine::ElfMachineMETAG,
            175 => ElfMachine::ElfMachineMcstElbrus,
            176 => ElfMachine::ElfMachineECOG16,
            177 => ElfMachine::ElfMachineCR16,
            178 => ElfMachine::ElfMachineETPU,
            179 => ElfMachine::ElfMachineSLE9X,
            180 => ElfMachine::ElfMachineL10M,
            181 => ElfMachine::ElfMachineK10M,
            183 => ElfMachine::ElfMachineAARCH64,
            185 => ElfMachine::ElfMachineAVR32,
            186 => ElfMachine::ElfMachineSTM8,
            187 => ElfMachine::ElfMachineTILE64,
            188 => ElfMachine::ElfMachineTILEPRO,
            189 => ElfMachine::ElfMachineMICROBLAZE,
            190 => ElfMachine::ElfMachineCUDA,
            191 => ElfMachine::ElfMachineTILEGX,
            192 => ElfMachine::ElfMachineCLOUDSHIELD,
            193 => ElfMachine::ElfMachineCorea1st,
            194 => ElfMachine::ElfMachineCorea2nd,
            195 => ElfMachine::ElfMachineARCV2,
            196 => ElfMachine::ElfMachineOPEN8,
            197 => ElfMachine::ElfMachineRL78,
            198 => ElfMachine::ElfMachineVIDEOCORE5,
            199 => ElfMachine::ElfMachine78KOR,
            200 => ElfMachine::ElfMachine56800EX,
            201 => ElfMachine::ElfMachineBA1,
            202 => ElfMachine::ElfMachineBA2,
            203 => ElfMachine::ElfMachineXCORE,
            204 => ElfMachine::ElfMachineMchpPic,
            205 => ElfMachine::ElfMachineINTELGT,
            210 => ElfMachine::ElfMachineKM32,
            211 => ElfMachine::ElfMachineKMX32,
            212 => ElfMachine::ElfMachineEMX16,
            213 => ElfMachine::ElfMachineEMX8,
            214 => ElfMachine::ElfMachineKVARC,
            215 => ElfMachine::ElfMachineCDP,
            216 => ElfMachine::ElfMachineCOGE,
            217 => ElfMachine::ElfMachineCOOL,
            218 => ElfMachine::ElfMachineNORC,
            219 => ElfMachine::ElfMachineCsrKalimba,
            220 => ElfMachine::ElfMachineZ80,
            221 => ElfMachine::ElfMachineVISIUM,
            222 => ElfMachine::ElfMachineFT32,
            223 => ElfMachine::ElfMachineMOXIE,
            224 => ElfMachine::ElfMachineAMDGPU,
            243 => ElfMachine::ElfMachineRISCV,
            247 => ElfMachine::ElfMachineBPF,
            252 => ElfMachine::ElfMachineCSKY,
            _ => ElfMachine::ElfMachineNONE,
        }
    }

    pub fn e_version(&self) -> ElfVersion {
        match self._e_version {
            1 => ElfVersion::ElfVersionCurrent,
            _ => ElfVersion::ElfVersionNone,
        }
    }
}

impl Default for ElfHeaderCommon {
    fn default() -> ElfHeaderCommon {
        ElfHeaderCommon {
            magic: [0;4],
            _class: 0,
            _data_encoding: 0,
            version: 0,
            os_abi: 0,
            abi_version: 0,
            pad: [0;7],
            _e_type: 0,
            _e_machine: 0,
            _e_version: 0,
        }
    }
}
